export const API_PREFIX = '/api';

export const ROUTES = {
  AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    ME: '/api/auth/me',
  },
  PATIENTS: '/api/patients',
  PATIENT: (id: string) => `/api/patients/${id}`,
  PATIENT_CHART_SUMMARY: (id: string) => `/api/patients/${id}/chart-summary`,
  PATIENT_CHECKOUT_HANDOFF: (id: string) => `/api/patients/${id}/checkout-handoff`,
  CHECKOUT_WORKLOAD: '/api/patients/workload/checkout',
  PATIENT_DOCUMENTS: (id: string) => `/api/patients/${id}/documents`,
  PATIENT_DOCUMENT: (patientId: string, documentId: string) => `/api/patients/${patientId}/documents/${documentId}`,
  PATIENT_DOCUMENT_ACCESS: (patientId: string, documentId: string) => `/api/patients/${patientId}/documents/${documentId}/access`,
  PATIENT_MEDICATIONS: (id: string) => `/api/patients/${id}/medications`,
  PATIENT_MEDICATION: (patientId: string, medicationId: string) => `/api/patients/${patientId}/medications/${medicationId}`,
  PATIENT_CARE_PLAN: (id: string) => `/api/patients/${id}/care-plan`,
  PATIENT_CARE_PLAN_ITEM: (patientId: string, itemId: string) => `/api/patients/${patientId}/care-plan/${itemId}`,
  PATIENT_LABS: (id: string) => `/api/patients/${id}/labs`,
  PATIENT_LAB: (patientId: string, labId: string) => `/api/patients/${patientId}/labs/${labId}`,
  PATIENT_ENCOUNTERS: (id: string) => `/api/patients/${id}/encounters`,
  PATIENT_ENCOUNTER: (patientId: string, encounterId: string) => `/api/patients/${patientId}/encounters/${encounterId}`,
  TASKS: '/api/tasks',
  TASK: (id: string) => `/api/tasks/${id}`,
  SCHEDULE: '/api/schedule',
  TODAY_QUEUE: '/api/schedule/today-queue',
  APPOINTMENT: (id: string) => `/api/schedule/${id}`,
  FAXES: '/api/faxes',
  FAX: (id: string) => `/api/faxes/${id}`,
  MESSAGES: '/api/messages',
  MESSAGE: (id: string) => `/api/messages/${id}`,
  THREAD: (id: string) => `/api/messages/threads/${id}`,
  WS: '/api/ws',
  HEALTH: '/api/health',
} as const;

export const WS_CHANNELS = {
  AUDIT: 'events:audit',
  TASK: 'events:task',
  FAX: 'events:fax',
  MESSAGE: 'events:message',
  SCHEDULE: 'events:schedule',
  SYSTEM: 'events:system',
} as const;
