export const API_PREFIX = '/api';

export const ROUTES = {
  AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    ME: '/api/auth/me',
  },
  PATIENTS: '/api/patients',
  PATIENT: (id: string) => `/api/patients/${id}`,
  PATIENT_CHART_SUMMARY: (id: string) => `/api/patients/${id}/chart-summary`,
  PATIENT_CHECKOUT_HANDOFF: (id: string) => `/api/patients/${id}/checkout-handoff`,
  PATIENT_CHECKOUT_HANDOFF_TASKS: (id: string) => `/api/patients/${id}/checkout-handoff/tasks`,
  CHECKOUT_WORKLOAD: '/api/patients/workload/checkout',
  PATIENT_DOCUMENTS: (id: string) => `/api/patients/${id}/documents`,
  PATIENT_DOCUMENT_UPLOAD: (id: string) => `/api/patients/${id}/documents/upload`,
  PATIENT_DOCUMENT_UPLOAD_CONFIRM: (id: string) => `/api/patients/${id}/documents/upload/confirm`,
  PATIENT_DOCUMENT: (patientId: string, documentId: string) => `/api/patients/${patientId}/documents/${documentId}`,
  PATIENT_DOCUMENT_ACCESS: (patientId: string, documentId: string) => `/api/patients/${patientId}/documents/${documentId}/access`,
  PATIENT_DOCUMENT_PROCESS: (patientId: string, documentId: string) => `/api/patients/${patientId}/documents/${documentId}/process`,
  PATIENT_PORTAL_ACCESS_CODE: (id: string) => `/api/patients/${id}/portal-access-code`,
  PATIENT_MEDICATIONS: (id: string) => `/api/patients/${id}/medications`,
  PATIENT_MEDICATION: (patientId: string, medicationId: string) => `/api/patients/${patientId}/medications/${medicationId}`,
  PATIENT_CARE_PLAN: (id: string) => `/api/patients/${id}/care-plan`,
  PATIENT_CARE_PLAN_ITEM: (patientId: string, itemId: string) => `/api/patients/${patientId}/care-plan/${itemId}`,
  PATIENT_LABS: (id: string) => `/api/patients/${id}/labs`,
  PATIENT_LAB: (patientId: string, labId: string) => `/api/patients/${patientId}/labs/${labId}`,
  PATIENT_ENCOUNTERS: (id: string) => `/api/patients/${id}/encounters`,
  PATIENT_ENCOUNTER: (patientId: string, encounterId: string) => `/api/patients/${patientId}/encounters/${encounterId}`,
  TASKS: '/api/tasks',
  TASK: (id: string) => `/api/tasks/${id}`,
  TASK_PATIENT_OUTREACH: (id: string) => `/api/tasks/${id}/patient-outreach`,
  TASK_PATIENT_OUTREACH_DELIVER: (id: string) => `/api/tasks/${id}/patient-outreach/deliver`,
  USERS: '/api/users',
  USER: (id: string) => `/api/users/${id}`,
  USER_ACCESS_REVIEW: '/api/users/access-review',
  USER_ACCESS_REVIEW_MARK: (id: string) => `/api/users/${id}/access-review`,
  SETTINGS: '/api/settings',
  SCHEDULE: '/api/schedule',
  TODAY_QUEUE: '/api/schedule/today-queue',
  APPOINTMENT: (id: string) => `/api/schedule/${id}`,
  APPOINTMENT_CONFLICT_CHECK: '/api/schedule/appointments/conflicts/check',
  APPOINTMENT_REMINDERS: (id: string) => `/api/schedule/appointments/${id}/reminders`,
  PROVIDER_AVAILABILITY: (providerId: string) => `/api/schedule/availability/${providerId}`,
  FAXES: '/api/faxes',
  FAX: (id: string) => `/api/faxes/${id}`,
  MESSAGES: '/api/messages',
  MESSAGE: (id: string) => `/api/messages/${id}`,
  THREAD: (id: string) => `/api/messages/threads/${id}`,
  WS: '/api/ws',
  HEALTH: '/api/health',
  PATIENT_ACCESS_HISTORY: (id: string) => `/api/audit/patients/${id}/access-history`,
  ANALYTICS_SUMMARY: '/api/analytics/summary',
  PILOT_READINESS: '/api/analytics/pilot-readiness',
  PILOT_READINESS_SEED: '/api/analytics/pilot-readiness/seed',
  BILLING_CASES: '/api/billing/cases',
  BILLING_CHARGE_REVIEW: '/api/billing/charge-review',
  BILLING_CASE_SUBMIT: (caseId: string) => `/api/billing/cases/${caseId}/submit`,
  BILLING_CASE_PAYMENT: (caseId: string) => `/api/billing/cases/${caseId}/payment`,
  BILLING_CASE_DENY: (caseId: string) => `/api/billing/cases/${caseId}/deny`,
  BILLING_CASE_TIMELINE: (caseId: string) => `/api/billing/cases/${caseId}/timeline`,
  BILLING_FROM_ENCOUNTER: (encounterId: string) => `/api/billing/cases/from-encounter/${encounterId}`,
  ELIGIBILITY_CHECK: (patientId: string) => `/api/billing/eligibility/${patientId}`,
  ELIGIBILITY_HISTORY: (patientId: string) => `/api/billing/eligibility/${patientId}/history`,
  PORTAL_INTAKE: '/api/portal-intake',
  PORTAL_INTAKE_APPLY: (id: string) => `/api/portal-intake/${id}/apply-to-patient`,
  PORTAL_INTAKE_APPOINTMENT: (id: string) => `/api/portal-intake/${id}/convert-appointment`,
  PORTAL_INTAKE_DOCUMENT: (id: string) => `/api/portal-intake/${id}/convert-document`,
  PORTAL_AUTH_LOGIN: '/api/portal/auth/login',
  PORTAL_AUTH_ME: '/api/portal/auth/me',
  PORTAL_PATIENT_INTAKE: '/api/portal/auth/intake',
  PORTAL_PATIENT_DOCUMENT_UPLOAD: '/api/portal/auth/documents/upload',
  PORTAL_PATIENT_DOCUMENT_UPLOAD_CONFIRM: '/api/portal/auth/documents/upload/confirm',
  ENCOUNTER_TEMPLATES: '/api/clinical/encounter-templates',
  INTEGRATION_CAPABILITIES: '/api/integration-capabilities',
  INTEGRATION_CONFIG: '/api/integrations/config',
  INTEGRATION_CONFIG_ITEM: (integration: string) => `/api/integrations/config/${integration}`,
  INTEGRATION_CONFIG_TEST: (integration: string) => `/api/integrations/config/${integration}/test`,
  LAUNCH_READINESS: '/api/launch-readiness',
  SESSION_POLICY: '/api/auth/session-policy',
} as const;

export const WS_CHANNELS = {
  AUDIT: 'events:audit',
  TASK: 'events:task',
  FAX: 'events:fax',
  MESSAGE: 'events:message',
  SCHEDULE: 'events:schedule',
  SYSTEM: 'events:system',
} as const;
