/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './router/routes/__root'
import { Route as StaffRouteImport } from './router/routes/staff'
import { Route as SetupRouteImport } from './router/routes/setup'
import { Route as RolesRouteImport } from './router/routes/roles'
import { Route as ReportsRouteImport } from './router/routes/reports'
import { Route as PortalMockRouteImport } from './router/routes/portal-mock'
import { Route as PortalIntakeRouteImport } from './router/routes/portal-intake'
import { Route as LoginRouteImport } from './router/routes/login'
import { Route as IntegrationsRouteImport } from './router/routes/integrations'
import { Route as BillingRouteImport } from './router/routes/billing'
import { Route as AssistantReviewRouteImport } from './router/routes/assistant-review'
import { Route as IndexRouteImport } from './router/routes/index'
import { Route as TasksIndexRouteImport } from './router/routes/tasks/index'
import { Route as SchedulingIndexRouteImport } from './router/routes/scheduling/index'
import { Route as PatientsIndexRouteImport } from './router/routes/patients/index'
import { Route as OperationsIndexRouteImport } from './router/routes/operations/index'
import { Route as MessagingIndexRouteImport } from './router/routes/messaging/index'
import { Route as FaxesIndexRouteImport } from './router/routes/faxes/index'
import { Route as PatientsPatientIdRouteImport } from './router/routes/patients/$patientId'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMockRoute = PortalMockRouteImport.update({
  id: '/portal-mock',
  path: '/portal-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIntakeRoute = PortalIntakeRouteImport.update({
  id: '/portal-intake',
  path: '/portal-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantReviewRoute = AssistantReviewRouteImport.update({
  id: '/assistant-review',
  path: '/assistant-review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingIndexRoute = SchedulingIndexRouteImport.update({
  id: '/scheduling/',
  path: '/scheduling/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingIndexRoute = MessagingIndexRouteImport.update({
  id: '/messaging/',
  path: '/messaging/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaxesIndexRoute = FaxesIndexRouteImport.update({
  id: '/faxes/',
  path: '/faxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant-review': typeof AssistantReviewRoute
  '/billing': typeof BillingRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/portal-intake': typeof PortalIntakeRoute
  '/portal-mock': typeof PortalMockRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/setup': typeof SetupRoute
  '/staff': typeof StaffRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/faxes/': typeof FaxesIndexRoute
  '/messaging/': typeof MessagingIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant-review': typeof AssistantReviewRoute
  '/billing': typeof BillingRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/portal-intake': typeof PortalIntakeRoute
  '/portal-mock': typeof PortalMockRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/setup': typeof SetupRoute
  '/staff': typeof StaffRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/faxes': typeof FaxesIndexRoute
  '/messaging': typeof MessagingIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant-review': typeof AssistantReviewRoute
  '/billing': typeof BillingRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/portal-intake': typeof PortalIntakeRoute
  '/portal-mock': typeof PortalMockRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/setup': typeof SetupRoute
  '/staff': typeof StaffRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/faxes/': typeof FaxesIndexRoute
  '/messaging/': typeof MessagingIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant-review'
    | '/billing'
    | '/integrations'
    | '/login'
    | '/portal-intake'
    | '/portal-mock'
    | '/reports'
    | '/roles'
    | '/setup'
    | '/staff'
    | '/patients/$patientId'
    | '/faxes/'
    | '/messaging/'
    | '/operations/'
    | '/patients/'
    | '/scheduling/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant-review'
    | '/billing'
    | '/integrations'
    | '/login'
    | '/portal-intake'
    | '/portal-mock'
    | '/reports'
    | '/roles'
    | '/setup'
    | '/staff'
    | '/patients/$patientId'
    | '/faxes'
    | '/messaging'
    | '/operations'
    | '/patients'
    | '/scheduling'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/assistant-review'
    | '/billing'
    | '/integrations'
    | '/login'
    | '/portal-intake'
    | '/portal-mock'
    | '/reports'
    | '/roles'
    | '/setup'
    | '/staff'
    | '/patients/$patientId'
    | '/faxes/'
    | '/messaging/'
    | '/operations/'
    | '/patients/'
    | '/scheduling/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantReviewRoute: typeof AssistantReviewRoute
  BillingRoute: typeof BillingRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  PortalIntakeRoute: typeof PortalIntakeRoute
  PortalMockRoute: typeof PortalMockRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  SetupRoute: typeof SetupRoute
  StaffRoute: typeof StaffRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  FaxesIndexRoute: typeof FaxesIndexRoute
  MessagingIndexRoute: typeof MessagingIndexRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  SchedulingIndexRoute: typeof SchedulingIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-mock': {
      id: '/portal-mock'
      path: '/portal-mock'
      fullPath: '/portal-mock'
      preLoaderRoute: typeof PortalMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-intake': {
      id: '/portal-intake'
      path: '/portal-intake'
      fullPath: '/portal-intake'
      preLoaderRoute: typeof PortalIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant-review': {
      id: '/assistant-review'
      path: '/assistant-review'
      fullPath: '/assistant-review'
      preLoaderRoute: typeof AssistantReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/': {
      id: '/scheduling/'
      path: '/scheduling'
      fullPath: '/scheduling/'
      preLoaderRoute: typeof SchedulingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging/': {
      id: '/messaging/'
      path: '/messaging'
      fullPath: '/messaging/'
      preLoaderRoute: typeof MessagingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faxes/': {
      id: '/faxes/'
      path: '/faxes'
      fullPath: '/faxes/'
      preLoaderRoute: typeof FaxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantReviewRoute: AssistantReviewRoute,
  BillingRoute: BillingRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  PortalIntakeRoute: PortalIntakeRoute,
  PortalMockRoute: PortalMockRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  SetupRoute: SetupRoute,
  StaffRoute: StaffRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  FaxesIndexRoute: FaxesIndexRoute,
  MessagingIndexRoute: MessagingIndexRoute,
  OperationsIndexRoute: OperationsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  SchedulingIndexRoute: SchedulingIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
