/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './router/routes/__root'
import { Route as LoginRouteImport } from './router/routes/login'
import { Route as IndexRouteImport } from './router/routes/index'
import { Route as TasksIndexRouteImport } from './router/routes/tasks/index'
import { Route as SchedulingIndexRouteImport } from './router/routes/scheduling/index'
import { Route as PatientsIndexRouteImport } from './router/routes/patients/index'
import { Route as OperationsIndexRouteImport } from './router/routes/operations/index'
import { Route as MessagingIndexRouteImport } from './router/routes/messaging/index'
import { Route as FaxesIndexRouteImport } from './router/routes/faxes/index'
import { Route as PatientsPatientIdRouteImport } from './router/routes/patients/$patientId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingIndexRoute = SchedulingIndexRouteImport.update({
  id: '/scheduling/',
  path: '/scheduling/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingIndexRoute = MessagingIndexRouteImport.update({
  id: '/messaging/',
  path: '/messaging/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaxesIndexRoute = FaxesIndexRouteImport.update({
  id: '/faxes/',
  path: '/faxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/faxes/': typeof FaxesIndexRoute
  '/messaging/': typeof MessagingIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/faxes': typeof FaxesIndexRoute
  '/messaging': typeof MessagingIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/faxes/': typeof FaxesIndexRoute
  '/messaging/': typeof MessagingIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/patients/$patientId'
    | '/faxes/'
    | '/messaging/'
    | '/operations/'
    | '/patients/'
    | '/scheduling/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/patients/$patientId'
    | '/faxes'
    | '/messaging'
    | '/operations'
    | '/patients'
    | '/scheduling'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/patients/$patientId'
    | '/faxes/'
    | '/messaging/'
    | '/operations/'
    | '/patients/'
    | '/scheduling/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  FaxesIndexRoute: typeof FaxesIndexRoute
  MessagingIndexRoute: typeof MessagingIndexRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  SchedulingIndexRoute: typeof SchedulingIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/': {
      id: '/scheduling/'
      path: '/scheduling'
      fullPath: '/scheduling/'
      preLoaderRoute: typeof SchedulingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging/': {
      id: '/messaging/'
      path: '/messaging'
      fullPath: '/messaging/'
      preLoaderRoute: typeof MessagingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faxes/': {
      id: '/faxes/'
      path: '/faxes'
      fullPath: '/faxes/'
      preLoaderRoute: typeof FaxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  FaxesIndexRoute: FaxesIndexRoute,
  MessagingIndexRoute: MessagingIndexRoute,
  OperationsIndexRoute: OperationsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  SchedulingIndexRoute: SchedulingIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
